[api]
    port = "8080"
    profile = "dev"
[db]
    driverName = "mysql"
    host = "localhost"
    port = "3306"
    user = "root"
    password = "7890123"
    name = "db_med_odonto"
    readTimeout = "30s"
    writeTimeout = "30s"
